- maintainersguide/index.md
This is intended to get the ball rolling on a discussion about how the Maintainers should be working. I've made a few assertions in here that represent my own opinion, and I think deserve some further debate.
> Create a new guide for maintainers for discussion

- roadmap/index.md
Basically changed a few words, to try to put more focus on the community, specifically in the 'who gets to write it', mention the community before the other stakeholders
> More focus on the community in wording

- _config.yml
Trying to clean up numbered lists
> Switch to the Slate theme

- technical/ChecklistForNewFeatureC++.md
rendering of source tree was inline, list with task was not correctly indented
> add code fence for better source tree display

- stylebook/index.md
- fix links to ui images
- fix some spelling errors
- remove double whitespace
- sanitize links to resource books
> Styleguide: fix image links, minor changes

- gettingstarted/index.md
- added markdown links otherwise they are not rendered by the theme
- detailed a bit some git instructions
> Small tweaks to getting started page

- stylebook/index.md
philosophy about not presenting user with non-functional tools
> Don't Show users tools that don't work.  solves #34

- gettingstarted/dependencies.md
- gettingstarted/index.md
Added some lines detailing packages relevant to building FreeCAD on Fedora.
> Getting Started on Fedora

- maintainersguide/index.md
List everyone in charge and their specialization
> Add the list of current maintainers

- roadmap/index.md
- roadmap/next.md
This page summarizes the goals for 1.0 release and links to relevant resources
> Next release Page for roadmap

- technical/automated_testing.md
some additional comments for us beginners.  Please check the first comment's accuracy.  Is App/AppTests/MappedNamePOSTFIXTEST.cpp correct?
> [Testing] add comments to c++ example

- designguide/index.md
To make it more consistent with others and remove unnecessary logo (an exception here and nowhere else).
> Small update to the Design Guide index.md

- index.md
The focus of the Design Guide is on UX/UI as a whole, not only on "visual elements".
> Update index.md with clearer title for the Design Guide

- technical/index.md
OCCT links I've found helpful when developing.
> Add useful OCCT links

- gettingstarted/dependencies.md
- technical/ObjectDeletion.md
- technical/PropertyChanges.md
- Add Arch Linux dependencies
- Some syntax fixes
>  Add Arch Linux dependencies

- technical/ReferenceLibrary.md
- technical/index.md
Add section for FPA reference lib.
> Add section for FPA reference lib

- gettingstarted/index.md
> Fix: Update relative links

- gettingstarted/VSCode.md
- gettingstarted/dependencies.md
- recommend pixi in `gettingstarted/VSCode`
> Update: Recommend Pixi for build

- gettingstarted/VSCode.md
- gettingstarted/dependencies.md
- Added pixi test script
- Added c++ executable test script
> Update: Add more test scripts

- maintainersguide/teams.md
Updated Design Working Group mission and contact.
> Update DWG Mission/Contact

- maintainersguide/index.md
I was only mentioned by my handle, I don't mind my name being public.
> Mention myself (kadet1090) by full name

- maintainersguide/teams.md
> Fix spelling

- designguide/naming.md
This includes guidance on how to apply title case adapted from the APA.
> Update language on Naming conventions

- designguide/glossary.md
- designguide/history-and-purpose.md
- designguide/index.md
- designguide/input-hints.md
- designguide/naming.md
- designguide/principles.md
- designguide/zones.md
- gettingstarted/CLion.md
- maintainersguide/teams.md
- roadmap/index.md
- technical/PythonStubsPackage.md
Fixed various wrong heading levels 
/ added 2 missing main headings.
> [ Fix ] Heading Levels
